// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/oauth": {
            "post": {
                "description": "Authenticate via Google OAuth. On success returns a signed JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "OAuth login",
                "parameters": [
                    {
                        "description": "OAuth code and provider info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.oauthLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ token: \u003cjwt\u003e }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "Auth service unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dev/login": {
            "post": {
                "description": "Returns a signed JWT for a seeded test account. Only available in dev environment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Dev login (development only)",
                "parameters": [
                    {
                        "description": "Role and seed number",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.devLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ token: \u003cjwt\u003e }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/driver": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve the driver profile of the authenticated user. Requires driver role JWT.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Get driver profile",
                "responses": {
                    "200": {
                        "description": "Driver profile",
                        "schema": {
                            "$ref": "#/definitions/contracts.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden: driver role required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Driver profile not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a driver profile for the authenticated user. Requires driver role JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Create driver profile",
                "parameters": [
                    {
                        "description": "Driver name and optional profile picture URL",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.createDriverRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created driver profile",
                        "schema": {
                            "$ref": "#/definitions/contracts.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or missing name",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden: driver role required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/driver/cars": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all cars registered to the authenticated driver. Requires driver role JWT.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "List cars",
                "responses": {
                    "200": {
                        "description": "List of cars",
                        "schema": {
                            "$ref": "#/definitions/contracts.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden: driver role required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register a car for the authenticated driver. Requires driver role JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drivers"
                ],
                "summary": "Add car",
                "parameters": [
                    {
                        "description": "Car plate and package slug (e.g. \\",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.createCarRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created car",
                        "schema": {
                            "$ref": "#/definitions/contracts.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Missing required fields",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden: driver role required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/trip/cancel": {
            "post": {
                "description": "Cancel a trip",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Cancel trip",
                "parameters": [
                    {
                        "description": "User ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.cancelTripRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cancelled trip",
                        "schema": {
                            "$ref": "#/definitions/contracts.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/trip/preview": {
            "post": {
                "description": "Calculate route geometry and available fare options before starting a trip",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Preview trip",
                "parameters": [
                    {
                        "description": "Pickup and destination coordinates",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.previewTripRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Route and fare options",
                        "schema": {
                            "$ref": "#/definitions/contracts.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/trip/start": {
            "post": {
                "description": "Create a trip from a previously previewed ride fare",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trips"
                ],
                "summary": "Start trip",
                "parameters": [
                    {
                        "description": "Selected fare and user ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.startTripRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created trip ID",
                        "schema": {
                            "$ref": "#/definitions/contracts.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/create": {
            "post": {
                "description": "Register a new user as a rider or driver",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.createUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created user",
                        "schema": {
                            "$ref": "#/definitions/contracts.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON or invalid role",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "contracts.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "contracts.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/contracts.APIError"
                }
            }
        },
        "main.cancelTripRequest": {
            "type": "object",
            "properties": {
                "userID": {
                    "type": "string"
                }
            }
        },
        "main.createCarRequest": {
            "type": "object",
            "properties": {
                "car_plate": {
                    "type": "string"
                },
                "package_slug": {
                    "type": "string"
                }
            }
        },
        "main.createDriverRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "profile_picture": {
                    "type": "string"
                }
            }
        },
        "main.createUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "description": "\"rider\" | \"driver\" — required",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "main.devLoginRequest": {
            "type": "object",
            "properties": {
                "role": {
                    "description": "\"rider\" | \"driver\"",
                    "type": "string"
                },
                "seed": {
                    "type": "integer"
                }
            }
        },
        "main.oauthLoginRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "provider": {
                    "description": "\"google\"",
                    "type": "string"
                },
                "redirect_uri": {
                    "type": "string"
                },
                "role": {
                    "description": "\"rider\" | \"driver\"",
                    "type": "string"
                }
            }
        },
        "main.previewTripRequest": {
            "type": "object",
            "properties": {
                "destination": {
                    "$ref": "#/definitions/types.Coordinate"
                },
                "pickup": {
                    "$ref": "#/definitions/types.Coordinate"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "main.startTripRequest": {
            "type": "object",
            "properties": {
                "rideFareID": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "types.Coordinate": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
