package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"ride-sharing/shared/env"
	"ride-sharing/shared/messaging"
	"ride-sharing/shared/tracing"

	httpSwagger "github.com/swaggo/http-swagger"
	_ "ride-sharing/services/api-gateway/docs" // generated by swag init
)

var (
	httpAddr    = env.GetString("HTTP_ADDR", ":8081")
	rabbitMqURI = env.GetString("RABBITMQ_URI", "amqp://admin:admin@rabbitmq:5672")
)

func main() {
	log.Println("Starting API Gateway")

	// Initialize Tracing
	tracerCfg := tracing.Config{
		ServiceName:    "api-gateway",
		Environment:    env.GetString("ENVIRONMENT", "development"),
		JaegerEndpoint: env.GetString("OTEL_ENDPOINT", "jaeger:4318"),
	}

	sh, err := tracing.InitTracer(tracerCfg)
	if err != nil {
		log.Fatalf("Failed to initialize the tracer: %v", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	defer sh(ctx)

	// Initialize shared gRPC clients
	app, err := InitializeClients()
	if err != nil {
		log.Fatalf("Failed to initialize gRPC clients: %v", err)
	}
	defer app.CloseAllClients()

	log.Println("Initialized gRPC clients")

	mux := http.NewServeMux()

	// RabbitMQ connection
	rabbitmq, err := messaging.NewRabbitMQ(rabbitMqURI)
	if err != nil {
		log.Fatal(err)
	}
	defer rabbitmq.Close()

	log.Println("Starting RabbitMQ connection")

	if err := rabbitmq.DeclareExchanges(); err != nil {
		log.Fatalf("Failed to declare exchanges: %v", err)
	}

	// Start queue consumers once at startup — they route messages by ownerID via connManager
	for _, q := range []string{
		messaging.DriverCmdTripRequestQueue,
		messaging.DriverTripRequestExpiredQueue,
		messaging.NotifyDriverNoDriversFoundQueue,
		messaging.NotifyDriverAssignmentQueue,
	} {
		consumer := messaging.NewQueueConsumer(rabbitmq, connManager, q)
		if err := consumer.Start(); err != nil {
			log.Fatalf("Failed to start consumer for queue %s: %v", q, err)
		}
		log.Printf("Started consumer for queue: %s", q)
	}

	// Swagger UI — available at http://localhost:8081/swagger/
	mux.Handle("/swagger/", httpSwagger.WrapHandler)

	// HTTP routes
	mux.Handle("POST /trip/preview", tracing.WrapHandlerFunc(handleTripPreview(app), "handleTripPreview"))
	mux.Handle("POST /trip/start", tracing.WrapHandlerFunc(handleTripStart(app), "handleTripStart"))
	mux.Handle("POST /trip/cancel", tracing.WrapHandlerFunc(handleTripCancel(app), "handleTripCancel"))
	mux.Handle("POST /user/create", tracing.WrapHandlerFunc(handleUserCreation(app), "handleUserCreation"))
	mux.Handle("POST /driver", tracing.WrapHandlerFunc(handleCreateDriver(app), "handleCreateDriver"))
	mux.Handle("GET /driver", tracing.WrapHandlerFunc(handleGetDriver(app), "handleGetDriver"))
	mux.Handle("POST /driver/cars", tracing.WrapHandlerFunc(handleCreateCar(app), "handleCreateCar"))
	mux.Handle("GET /driver/cars", tracing.WrapHandlerFunc(handleListCars(app), "handleListCars"))
	mux.Handle("POST /auth/oauth", tracing.WrapHandlerFunc(proxyAuth("/auth/oauth"), "proxyAuthOAuth"))
	mux.Handle("POST /dev/login", tracing.WrapHandlerFunc(proxyAuth("/dev/login"), "proxyDevLogin"))
	mux.Handle("/ws/drivers", tracing.WrapHandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handleDriverWebSocket(w, r, rabbitmq, app)
	}, "/ws/drivers"))
	mux.Handle("/ws/riders", tracing.WrapHandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		handleRiderWebSocket(w, r, rabbitmq, app)
	}, "/ws/riders"))

	server := &http.Server{
		Addr:    httpAddr,
		Handler: enableCORS(mux),
	}

	serverErrors := make(chan error, 1)

	go func() {
		log.Printf("Serve listening on %s", httpAddr)
		serverErrors <- server.ListenAndServe()
	}()

	shutdown := make(chan os.Signal, 1)
	signal.Notify(shutdown, os.Interrupt, syscall.SIGTERM)

	select {
	case err := <-serverErrors:
		log.Printf("Error starting the server: %v", err)
	case sig := <-shutdown:
		log.Printf("Server is shutting down due to %v signal", sig)

		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		if err := server.Shutdown(ctx); err != nil {
			log.Printf("Could not  stop the server graceful: %v", err)
			server.Close()
		}
	}

}
